# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_remove_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='location_taken',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='images.Location'),
            preserve_default=False,
        ),
    ]
