# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20180507_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_taken',
            field=models.TextField(verbose_name=images.models.Location),
        ),
    ]
