# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20180507_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location_taken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Location'),
        ),
    ]
