# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20180507_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripton',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
