# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-09 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_auto_20180509_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_id',
            name='post_id',
        ),
        migrations.DeleteModel(
            name='Post_id',
        ),
    ]
